---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)

library(shiny)
```


```{r load_data}
#read and clean the data
nynoaadat = read_csv("./data/nynoaadat.csv") %>%
  clean_names() %>% 
  separate(.,date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = as.numeric(month),
         year = as.numeric(year))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
#place code for widgets in the sidebar

station = nynoaadat %>% distinct(id) %>% pull()

# selectInput widget
selectInput("Station_choice", label = h3("Select ID"),
            choices = station, selected = "USW00094794")

max_year = max(nynoaadat$year)
min_year = min(nynoaadat$year)

# sliderInput widget
sliderInput("year_range", label = h3("Choose year range"), min = min_year, 
        max = max_year, value = c(min_year, max_year))
```


This `flexdashboard` with Shiny was made for [Jeff Goldsmith's Data Science I class, Homework 6](http://jeffgoldsmith.com/DSI/homework_6.html). The data come from [NOAA National Climatic Data Center](https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.ncdc:C00861), which provides public access to weather data from some weather stations. 


Row 
-----------------------------------------------------------------------

### Scatterplot of average max temperature against average min temperature

```{r}
#make interactive scatter plot
renderPlotly({
  nynoaadat %>% 
  filter(id == input$Station_choice, 
         year %in% input$year_range[1]:input$year_range[2]) %>%
  mutate(tmax = as.numeric(tmax)/10, tmin = as.numeric(tmin)/10) %>% 
  group_by(year, month) %>% 
  mutate(maximum_temperature = mean(tmax),
         minimum_temperature = mean(tmin)) %>% 
  mutate(month_str = month.name[month],
         text_label = str_c("Year: ",year,'; Month: ', month_str)) %>%
  plot_ly(x = ~minimum_temperature, y =  ~maximum_temperature, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~month_str,
          text = ~text_label) %>% 
    layout(xaxis = list(title = "Minimum temperature"),
           yaxis = list(title = "Maximum temperature"))
  })
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Boxplot of snowfall distribution of each month

```{r}
#make interactive boxplot
renderPlotly({
    nynoaadat %>%
    filter(id == input$Station_choice, 
           year %in% input$year_range[1]:input$year_range[2]) %>%
    filter(snow > 0 & snow < 100) %>% 
    group_by(month) %>% 
    mutate(med_snow = median(snow)) %>% 
    ungroup(month) %>% 
    mutate(month_str = month.abb[month],
         month_str = fct_reorder(month_str, med_snow)) %>% 
    rename(snowfall = snow) %>% 
    plot_ly(y = ~snowfall, color = ~month_str, type = "box") %>%
    layout(yaxis = list(title = "Snowfall"))
})

```


### Barplot of average snowfall

```{r}
#make interactive bar plot
renderPlotly({
    nynoaadat %>%
    filter(id == input$Station_choice, 
           year %in% input$year_range[1]:input$year_range[2]) %>%
    filter(snow > 0 & snow < 100) %>%
    mutate(year = as.factor(year)) %>%
    group_by(year) %>% 
    mutate(average_snallfall = round(mean(snow),3), 
           text_label = str_c("Year: ",year,'; Average Snowfall: ',average_snallfall)) %>%
    plot_ly(x = ~year, y = ~average_snallfall, type = "bar",
           color = ~year, 
           text = ~text_label) %>%
    layout(yaxis = list(title = "Snowfall"),
           xaxis = list(title = "", tickangle = 90))
})

```

